FROM opensearchproject/opensearch:2.12.0
# Install analysis-icu plugin
#RUN /usr/share/opensearch/bin/opensearch-plugin install analysis-icu
# Install analysis-phonetic plugin
#RUN /usr/share/opensearch/bin/opensearch-plugin install analysis-phonetic